name: CI
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [development, main, master, feat/*, fix/*]
    paths: ["**.js", "**.ts", ".json", "**.sol"]
  pull_request:
    branches: [development, main, master, feat/*, fix/*]
    paths: ["**.js", "**.ts", ".json", "**.sol"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Tests
        env:
          NODE_URL: ${{ secrets.NODE_URL }}
        run: |
          npm install --no-lockfile --force
          npm run prettier
          npx hardhat typechain
          npx hardhat test